name:                story
version:             0.1.0.0
github:              "stothardj/story"
license:             BSD3
author:              "Jake Stothard"
maintainer:          "stothardj@gmail.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stothardj/story#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
library:
  source-dirs: src

executables:
  story-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - story

tests:
  story-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - story
